services:
  db:
    container_name: db
    image: postgres
    volumes:
      - wild_league_dev:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: wild_league_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    networks:
      - wildleague

  api:
    image: mileschou/lapis:alpine
    platform: linux/amd64
    container_name: wildleague
    restart: unless-stopped
    command: sh -c "lapis serve"
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    working_dir: /api
    volumes:
      - .:/api
    networks:
      - wildleague

networks:
  wildleague:
    external: true

volumes:
  wild_league_dev:
