# fly.toml app configuration file generated for wildleague on 2023-08-24T11:00:02-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wildleague"
primary_region = "gru"

[build]

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
